import { getDrafts } from './actions'
import { DraftsList } from './components/drafts-list'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card'
import { FileText } from 'lucide-react'

export default async function DraftsPage() {
  const drafts = await getDrafts()

  return (
    <div className="container mx-auto py-6 space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-3xl font-bold">Generated Drafts</h1>
          <p className="text-muted-foreground">
            Drafts generated by the Deep Agent from your email analysis
          </p>
        </div>
      </div>

      {drafts.length === 0 ? (
        <Card className="bg-muted/50">
          <CardContent className="flex flex-col items-center justify-center py-12">
            <FileText className="h-12 w-12 text-muted-foreground mb-4" />
            <CardTitle className="text-xl mb-2">No Drafts Yet</CardTitle>
            <CardDescription className="text-center max-w-md">
              Drafts will appear here when you use the Deep Agent strategy with draft generation enabled.
              Go to your agent configuration and select &quot;Deep Agent&quot; as the content retrieval strategy,
              then enable draft generation.
            </CardDescription>
          </CardContent>
        </Card>
      ) : (
        <DraftsList drafts={drafts} />
      )}
    </div>
  )
}

